
project:
  title: "ManoptExamples.jl"
  output-dir: ../docs/src/examples
  render:
    - "*.qmd"
    - "!Constrained-Mean-H2.qmd"
    - "!Constrained-Mean-Hn.qmd"
    - "!Difference-of-Convex-Benchmark.qmd"
    - "!HyperparameterOptimization.qmd"
    - "!RCBM-Median.qmd"
    - "!Spectral-Procrustes.qmd"
    - "!NCRPG-Row-Sparse-Low-Rank.qmd"
    - "!H2-Signal-TV.qmd"
    - "!CRPG-Convex-SPD.qmd"
    - "!CRPG-Sparse-Approximation.qmd"
    - "!CRPG-Constrained-Mean-Hn.qmd"
    - "!NCRPG-Grassmann.qmd"
    - "!NCRPG-Sparse-PCA.qmd"

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
fig-format: png

execute:
  freeze: auto
  eval: true
  echo: true
  output: true
  keep-md: true

format:
  commonmark:
    variant: +pipe_tables+tex_math_dollars
    wrap: preserve

engines: ['julia']
