---
title: "A Geodesically Convex Example on the Sphere"
author: "Paula John, Hajg Jasa"
date: 06/15/2026
---

## Introduction

In this example we compare the Convex Riemannian Proximal Gradient (CRPG) method [BergmannJasaJohnPfeffer:2025:2](@cite) with both a constant and a backtracked step size strategy on the sphere.
This example reproduces the results from [BergmannJasaJohnPfeffer:2025:2](@cite), Section 6.2.

```{julia}
#| echo: false
#| code-fold: true
#| output: false
using Pkg;
cd(@__DIR__)
Pkg.activate("."); # for reproducibility use the local tutorial environment.

Pkg.develop(path="../") # a trick to work on the local dev version

export_orig = true
export_table = true
export_result = true
benchmarking = true

experiment_name = "CRPG-Sphere-Example"
results_folder = joinpath(@__DIR__, experiment_name)
!isdir(results_folder) && mkdir(results_folder)
```

```{julia}
#| output: false
using PrettyTables
using BenchmarkTools
using CSV, DataFrames
using ColorSchemes, Plots, LaTeXStrings, CairoMakie, Chairmarks
using Random, LinearAlgebra, LRUCache
using ManifoldDiff, Manifolds, Manopt, ManoptExamples
import ColorSchemes.tol_vibrant
```

## The Problem

Let $\mathcal M = \mathbb S^2$ be the $2$-dimensional hyperbolic space.

Let $g \colon \mathcal M \to \mathbb R$ be defined by

```math
g(p) = \frac{1}{2} \sum_{j = 1}^N w_j \, \mathrm{dist}(p, q_j)^2,
```
where $w_j$, $j = 1, \ldots, N$ are positive weights such that $\sum_{j = 1}^N w_j = 1$, and $\{q_1,\ldots,q_N\} \in \mathcal M$ denote $N = 1000$ Gaussian random data points.

Observe that the function $g$ is geodesically convex with respect to the Riemannian metric on $\mathcal M$ on balls of radius smaller than $\frac{\pi}{2}$.

Let now $\bar q$ be a given point, and let $h \colon \mathcal M \to \mathbb R$ be defined by

```math
h(p) = \tau \mathrm{dist}(p, \bar q),
```

for some $\tau > 0$.
We define our total objective function as $f = g + h$.
Notice that this objective function is also geodesically convex with respect to the Riemannian metric on $\mathcal M$.
The goal is to find the minimizer of $f$ on $\mathcal M$.


## Numerical Experiment

We initialize the experiment parameters, as well as some utility functions.
```{julia}
#| output: false
random_seed = 42

dims = [100, 500, 1000, 5000]
num_tests = 10

N   = 1000 # Number of points
τ   = 0.1  # weight parameter
max_it          = 1000
stop            = 1e-5
min_stepsize_bt = 1e-8

contraction_factor = 0.5
warm_start_factor = 2.0
# Choose a radius < pi/4
# The smaller the diameter of our set, the larger we can choose λ 
radius = pi/6
```
First we define the objective and related quantities
```{julia}
#| output: false
# Objective, gradient, and proxes
_g(S, p, qs) = sum(distance(S, p, qk)^2 for qk in qs) / (2 * length(qs))
get_g(qs) = (S, p) -> _g(S, p, qs)
#
get_h(q_bar, τ) = (S, p) -> τ * distance(S, p, q_bar)
#
_grad_g(S, p, qs) = -sum(log(S, p, qk) for qk in qs) / length(qs)
get_grad_g(qs) = (S, p) -> _grad_g(S, p, qs)
#
function _prox(S, λ, p, q_bar, τ)
    if distance(S,p,q_bar) <= λ*τ
        return q_bar
    end 
    V = log(S,p,q_bar)
    return exp(S, p, λ * τ * V/norm(V))
end 
get_prox(q_bar, τ) = (S, λ, p) -> _prox(S, λ, p, q_bar, τ)
#
f(M, p, q) = g(M, p) + h(M, p, q)
```
and then generate the problem data 
```{julia}
# Generate points and data
function generate_point(S, anchor, radius)
    X = rand(S; vector_at = anchor)
    return exp(S, anchor, rand()*radius*X/norm(X))
end 
function generate_data(S, radius; N=1000)
    anchor = rand(S)
    start = generate_point(S, anchor, radius)
    q_bar = generate_point(S, anchor, radius)
    qs    = [generate_point(S, anchor, radius) for i in 1:N]
    return start, q_bar, qs
end 
```
We now define some functions related to the stepsize selection
```{julia}
# Stepsize calculation
get_λ_δ(α1, α2, αg, δ) = (sqrt(4*(α2 - α1)^2 + 1/(2 + δ)^2 * αg^2) - 2 * (α2 - α1)) / (2 * αg^2)
get_ζ_δ(δ) = pi/(2 + δ) * cot(pi/(2 + δ))
#
function get_const_stepsize(radius, τ)
    # α1 ≤ h(p) ≤ α2 ∀p ∈ B(anchor, radius)
    α1 = 0.0
    α2 = τ * 2 * radius
    # ||grad_g(p)|| ≤ αg ∀p ∈ B(anchor, radius)
    αg = 2 * radius 
    Lg = 1.0
    #calc opt δ for constant stepsize
    δ_grid = 0.0:0.001:0.4
    vals = [min(get_λ_δ(α1, α2, αg, δ),get_ζ_δ(δ)/Lg) for δ in 0.0:0.001:0.4]
    λ_const, max_idx = findmax(vals)
    return λ_const, δ_grid[max_idx]
end 
#
function get_initial_stepsize(radius, τ, δ = 1e-8)
    # α1 ≤ h(p) ≤ α2 ∀p ∈ B(anchor, radius)
    α1 = 0.0
    α2 = τ * 2 * radius
    # ||grad_g(p)|| ≤ αg ∀p ∈ B(anchor, radius)
    αg = 2 * radius 
    #calc s for backtracking: we need s < λ_δ
    s = get_λ_δ(α1, α2, αg, δ)
    return s 
end 
```
Since the stepsizes are independent of the dimension, we define them here, in conjunction with the parameter $\delta$ used for the backtracking
```{julia}
λ_const, δ = get_const_stepsize(radius, τ)
δ_bt = 0.2
λ_init = get_initial_stepsize(radius, τ, δ_bt)
```
We introduce some keyword arguments for the solvers we will use in this experiment
```{julia}
#| output: false
# Solver arguments for backtracking
pgm_kwargs(contraction_factor, initial_stepsize, warm_start_factor) = [
    :record => [:Iteration, :Cost, :Iterate],
    :return_state => true,
    :stepsize => ProximalGradientMethodBacktracking(;
        contraction_factor=contraction_factor,
        strategy=:convex,
        initial_stepsize=initial_stepsize,
        stop_when_stepsize_less=atol,
        warm_start_factor=warm_start_factor,
    ),
    :stopping_criterion => StopWhenAny(
        StopWhenGradientMappingNormLess(atol), StopAfterIteration(max_iters)
    ),
]
pgm_bm_kwargs(contraction_factor, initial_stepsize, warm_start_factor) = [
    :record => [:Iteration, :Cost, :Iterate],
    :return_state => true,
    :stepsize => ProximalGradientMethodBacktracking(;
        contraction_factor=contraction_factor,
        strategy=:convex,
        initial_stepsize=initial_stepsize,
        stop_when_stepsize_less=atol,
        warm_start_factor=warm_start_factor,
    ),
    :stopping_criterion => StopWhenAny(
        StopWhenGradientMappingNormLess(atol), StopAfterIteration(max_iters)
    ),
]
# Solver arguments for constant stepsize
pgm_kwargs_constant(stepsize) = [
    :record => [:Iteration, :Cost, :Iterate],
    :return_state => true,
    :stepsize => ConstantLength(stepsize),
    :stopping_criterion => StopWhenAny(
        StopWhenGradientMappingNormLess(atol), StopAfterIteration(max_iters)
    ),
]
pgm_bm_kwargs_constant(stepsize) = [
    :record => [:Iteration, :Cost, :Iterate],
    :return_state => true,
    :stepsize => ConstantLength(stepsize),
    :stopping_criterion => StopWhenAny(
        StopWhenGradientMappingNormLess(atol), StopAfterIteration(max_iters)
    ),
]
```

Before running the experiments, we initialize data collection functions that we will use later
```{julia}
#| output: false
# Header for the dataframe
list = [ 
  "Dim"        => Int64[],
  "Stepsize"   => Float64[],
  "Time"       => Float64[],
  "Iterations" => Int64[], 
  "Objective"  => Float64[]
]

df_const = DataFrame(list, makeunique=true) 
df_bt    = DataFrame(list, makeunique=true)


global col_names_1 = [
    :Dimension,
    :Iterations_1,
    :Time_1,
    :Cost_1,
    :Iterations_2,
    :Time_2,
    :Cost_2,
]
col_types_1 = [
    Int64,
    Int64,
    Float64,
    Float64,
    Int64,
    Float64,
    Float64,
]
named_tuple_1 = (; zip(col_names_1, type[] for type in col_types_1 )...)
# Function for initializing the dataframe
function initialize_dataframes(
    results_folder,
    experiment_name,
    named_tuple_1,
)
    A1 = DataFrame(named_tuple_1)
    CSV.write(
        joinpath(
            results_folder,
            experiment_name *
            "-Comparisons.csv",
        ),
        A1;
        header=false,
    )
    return A1
end
```

```{julia}
#| output: false
function export_dataframes(
    M,
    records,
    times,
)
    B1 = DataFrame(;
        Dimension=manifold_dimension(M),
        Iterations_1=maximum(first.(records[1])),
        Time_1=times[1],
        Cost_1=minimum([r[2] for r in records[1]]),
        Iterations_2=maximum(first.(records[2])),
        Time_2=times[2],
        Cost_2=minimum([r[2] for r in records[2]]),
    )
    return B1
end
function write_dataframes(
    B1,
    results_folder,
    experiment_name,
)
    CSV.write(
        joinpath(
            results_folder,
            experiment_name *
            "-Comparisons.csv",
        ),
        B1;
        append=true,
    )
end
```

```{julia}
#| output: false
for dim in dims 
    S = Sphere(dim)
    time_bt = 0.0
    time_const = 0.0

    iterations_bt = 0
    iterations_const = 0
    
    objective_bt = 0.0
    objective_const = 0.0

    
    for i in 1:num_tests
        Random.seed!(1520+i)
        start, q_bar, qs = generate_data(S, radius)

        g = get_g(qs)
        h = get_h(q_bar, τ)
        f(S, p) = g(S, p) + h(S, p)
        grad_g = get_grad_g(qs)
        prox = get_prox(q_bar, τ)
        rec_const = proximal_gradient_method(S, f, g, grad_g, start;
                            prox_nonsmooth =prox, 
                            stepsize = ConstantLength(λ_const),
                            record=[:Iteration, :Iterate],
                            return_state=true,
                            stopping_criterion = StopAfterIteration(max_it)| StopWhenGradientMappingNormLess(stop)
        )
        bm_const = @benchmark proximal_gradient_method($S, $f, $g, $grad_g, $start;
                            prox_nonsmooth = $prox, 
                            stepsize = ConstantLength($λ_const),
                            stopping_criterion = StopAfterIteration($max_it)| StopWhenGradientMappingNormLess($stop)
        )
        rec_CRPG_bt = proximal_gradient_method(S, f, g, grad_g, start;
                            prox_nonsmooth =prox, 
                            stepsize = ProximalGradientMethodBacktracking(; 
                                                        strategy=:convex, 
                                                        initial_stepsize=λ_init, 
                                                        stop_when_stepsize_less = min_stepsize_bt,
                                                        δ=δ_bt,
                                                        contraction_factor=contraction_factor,
                                                        warm_start_factor=warm_start_factor,
                                                        k_max=1.0,),
                            record=[:Iteration, :Iterate],
                            return_state=true,
                            stopping_criterion =    StopAfterIteration(max_it)| StopWhenGradientMappingNormLess(stop)
        )
        bm_bt = @benchmark proximal_gradient_method($S, $f, $g, $grad_g, $start;
                            prox_nonsmooth = $prox, 
                            stepsize = ProximalGradientMethodBacktracking(;
                                strategy=:convex,
                                initial_stepsize=$λ_init,
                                stop_when_stepsize_less = $min_stepsize_bt,
                                δ=$δ_bt,
                                contraction_factor=$contraction_factor,
                                warm_start_factor=$warm_start_factor,
                                k_max=$1.0,
                            ),
                            stopping_criterion = StopAfterIteration($max_it)| StopWhenGradientMappingNormLess($stop)
        )

        it_const, res_const = get_record(rec_const)[end]
        it_bt, res_bt       = get_record(rec_CRPG_bt)[end]

        t_const = median(bm_const).time/1e9
        t_bt    = median(bm_bt).time/1e9
        
        println("dim: ", dim, " bt: ", t_bt, " const: ", t_const, " it_bt: ", it_bt, " it_const: ", it_const)
        objective_bt += f(S, res_bt)
        objective_const += f(S, res_const)
        time_bt += t_bt
        time_const += t_const
        iterations_bt += it_bt
        iterations_const += it_const
    end 

    push!(df_const, [dim, λ_const, time_const/num_tests, iterations_const/num_tests, objective_const/num_tests])
    push!(df_bt, [dim, λ_init, time_bt/num_tests, iterations_bt/num_tests, objective_bt/num_tests])
end 
```
# TODO print correct table 
We can take a look at how the algorithms compare to each other in their performance with the following tables.
The first table showcases the algorithm run with a constant stepsize...
```{julia}
# | echo: false
# | code-fold: true
# | output: asis
benchmarking && pretty_table(df_const; backend = :markdown, column_labels = list)
```
... while the second table showcases the algorithm run with a backtracked stepsize
```{julia}
# | echo: false
# | code-fold: true
# | output: asis
benchmarking && pretty_table(df_bt; backend = :markdown, column_labels = list)
```
```{julia}
#| output: false
#| echo: false
#| code-fold: true
df_res = DataFrame(
  "Dim"        => Dims, 
  "Iter_const" => df_const.Iterations,
  "Time_const" => df_const.Time,
  "Obj_const"  => df_const.Objective,
  "Iter_bt"    => df_bt.Iterations,
  "Time_bt"    => df_bt.Time,
  "Obj_bt"     => df_bt.Objective
)

CSV.write(joinpath(results_folder, experiment_name * "-results.csv"), df_res; delim=",", header=false)
```

## Test with different parameters

We now test CRPG on the same problem, but with different radii and different values of $\delta$.
We start by introducing these parameters
```{julia}
radii = [pi/5, pi/8]
# (radius, algorithm, δ) → error vector
#   algorithm = :CONST for constant stepsize
#               :BT    for back‑tracking
#   δ is `missing` for the constant‑stepsize runs
results = Dict{Tuple{Float64, Symbol, Union{Missing, Float64}}, Vector{Float64}}()
```
As well as a function to save the generated data
```{julia}
function write_csv(radius::Float64, algo::Symbol, out_path::String)
    # 5.1  Filter the dictionary for the wanted radius & algorithm = :BT
    bt_entries = [(δ, vec) for ((r, alg, δ), vec) in results
                  if r == radius && alg == algo]
    sort!(bt_entries, by = x -> x[1]) # sort by delta 
    max_len = maximum(length(v) for (_, v) in bt_entries)
    df      = DataFrame(Iter = 1:max_len)
    # Add one column per δ
    for (δ, vec) in bt_entries
        δ = round(δ, digits=3)
        col_name = Symbol("delta$(δ)")                
        padded   = vcat(vec, fill(missing, max_len - length(vec)))
        df[!, col_name] = padded
    end
    CSV.write(out_path, df; delim=",", writeheader=true)
end
```


And now we run the different experiments
```{julia}
for radius in radii
    Random.seed!(1520)
    start, q_bar, qs = generate_data(S, radius; N = N)
    h = get_h(q_bar, τ)
    g = get_g(qs)
    f = (S, p) -> g(S, p) + h(S, p)
    grad_g = get_grad_g(qs)
    prox = get_prox(q_bar, τ)
    # constant stepsize 
    λ_const, δ_opt = get_const_stepsize(radius, τ)
    rec_const = proximal_gradient_method(S, f, g, grad_g, start;
                                prox_nonsmooth =prox, 
                                stepsize = ConstantLength(λ_const),
                                record=[:Iteration, :Iterate],
                                return_state=true,
                                stopping_criterion =    StopAfterIteration(max_it)| StopWhenGradientMappingNormLess(stop)
    )
    iters_const = get_record(rec_const, :Iteration, :Iterate)
    prepend!(iters_const, [start])    
    obj_const = [f(S, it) for it in iters_const]
    err_const = [obj_const[i] - obj_const[end] for i in 1:length(obj_const)-1]
    # normalise by the first error
    err_const ./= err_const[1]

    results[(radius, :CONST, δ_opt)] = err_const

    # backtracking
    δs_bt = [round(δ_opt, digits=2)-0.01, round(δ_opt, digits=2), round(δ_opt, digits=2)+0.2]

    for δ_bt in δs_bt
        λ_init = get_initial_stepsize(radius, τ, δ_bt)
        rec_bt = proximal_gradient_method(S, f, g, grad_g, start;
                                    prox_nonsmooth =prox, 
                                    stepsize = ProximalGradientMethodBacktracking(;
                                        strategy=:convex,
                                        initial_stepsize=λ_init,
                                        stop_when_stepsize_less = min_stepsize_bt,
                                        contraction_factor=contraction_factor,
                                        warm_start_factor=warm_start_factor,
                                        δ=δ_bt,
                                        k_max=1.0,
                                    ),
                                    record=[:Iteration, :Iterate],
                                    return_state=true,
                                    stopping_criterion =    StopAfterIteration(max_it)| StopWhenGradientMappingNormLess(stop)
        )
        iters_bt = get_record(rec_bt, :Iteration, :Iterate)
        prepend!(iters_bt, [start])
        obj_bt = [f(S, it) for it in iters_bt]
        err_bt = [obj_bt[i] - obj_bt[end] for i in 1:length(obj_bt)-1]
        err_bt ./= err_bt[1]
        results[(radius, :BT, δ_bt)] = err_bt
    end 
end 
```
```{julia}
#| output: false
#| echo: false
#| code-fold: true
write_csv(radii[1], :BT, joinpath(results_folder, experiment_name * "results-02pi-radius-bt.csv"))
write_csv(radii[2], :BT, joinpath(results_folder, experiment_name * "results-0125pi-radius-bt.csv"))

write_csv(radii[1], :CONST, joinpath(results_folder, experiment_name * "results-02pi-radius-const.csv"))
write_csv(radii[2], :CONST, joinpath(results_folder, experiment_name * "results-0125pi-radius-const.csv"))
```

Lastly, we plot the rate of decay of the function values for these experiments
<!-- TODO finish plotting -->
```{julia}
#| output: false
function plot_convergence(
    stats,
    dimensions=[2],
)
    # Extract the results for the specified dimensions
    crpg_cn = [stats[:CRPG_CN][d] for d in dimensions]
    crpg_bt = [stats[:CRPG_BT][d] for d in dimensions]

    figs = Vector{Figure}()

    for i in 1:length(crpg_cn)

        # Get the solvers' results and records
        # crpg_cn_result = crpg_cn[i][:Result]
        crpg_cn_record = crpg_cn[i][:Cost]

        # crpg_bt_result = crpg_bt[i][:Result]
        crpg_bt_record = crpg_bt[i][:Cost]


        # Calculate the minimum cost for relative error
        min_cost_crpg_cn = minimum(crpg_cn_record)
        min_cost_crpg_bt = minimum(crpg_bt_record)

        # Create vectors for plotting
        iterations_crpg_cn = 1:crpg_cn[i][:Iteration]
        iterations_crpg_bt = 1:crpg_bt[i][:Iteration]

        # Get initial error for scaling reference lines
        relative_errors_crpg_cn = max.(crpg_cn_record .- min_cost_crpg_cn, 0)
        initial_error_crpg_cn = relative_errors_crpg_cn[1]

        relative_errors_crpg_bt = max.(crpg_bt_record .- min_cost_crpg_bt, 0)
        initial_error_crpg_bt = relative_errors_crpg_bt[1]

        initial_error = max(
            initial_error_crpg_cn,
            initial_error_crpg_bt,
        )

        iterations = max(
            iterations_crpg_cn,
            iterations_crpg_bt,
        )

        # Create reference trajectories
        # O(1/k)
        ref_rate_1 = [initial_error/k for k in iterations]
        # O(1/2^k)
        ref_rate_2k = [initial_error/2^k for k in iterations]

        # Create the convergence plot
        fig = Figure()
        ax = Axis(fig[1, 1],
            title =L"\mathcal{P}(%$(dimensions[i]))",
            xlabel =L"\text{Iterations }(k)",
            ylabel =L"f(p_k) - f_*",
            # xscale=log10,
            yscale=log10,
            yminorticksvisible = true,
            yminorgridvisible = true,
            yminorticks = IntervalsBetween(8),
        )
        lines!(
            ax,
            iterations_crpg_cn,
            abs.(relative_errors_crpg_cn);
            label="CRPG, constant step",
            linewidth=2,
            color=tol_vibrant[1],
        )
        lines!(
            ax,
            iterations_crpg_bt,
            abs.(relative_errors_crpg_bt);
            label="CRPG, backtracked step",
            linewidth=2,
            color=tol_vibrant[5],
        )
        lines!(
            ax,
            iterations,
            abs.(ref_rate_1);
            linestyle=:dash,
            linewidth=1.5,
            color=:blue,
            label=L"\mathcal O\left(k^{-1}\right)"
        )
        lines!(
            ax,
            iterations,
            abs.(ref_rate_2k);
            linestyle=:dot,
            linewidth=1.5,
            color=:black,
            label=L"\mathcal O\left(2^{-k}\right)"
        )
        fig[1, 2] = Legend(fig, ax, framevisible = true)
        fig

        push!(figs, fig)
    end
    return figs
end
figs = plot_convergence(stats)
```

```{julia}
#| code-fold: true
for fig in figs
    display(fig)
end
```

This is in line with the convergence rates of the CRPG method in the geodesically convex setting, as shown in [BergmannJasaJohnPfeffer:2025:2](@cite), Theorem 4.7.

## Technical details

This tutorial is cached. It was last run on the following package versions.

```{julia}
#| code-fold: true
#| code-summary: "Package versions"
#| echo: false
using Pkg
Pkg.status()
```

```{julia}
#| echo: false
#| output: asis
using Dates
println("This tutorial was last rendered $(Dates.format(now(), "U d, Y, H:M:S")).");
```

## Literature

````{=commonmark}
```@bibliography
Pages = ["CRPG-Convex-SPD.md"]
Canonical=false
```
````
